### ISSUE TITLE
feat: add monospace font-family type in fallback option

### ISSUE THREAD

**Issue by nikvoblikov** [pixel-point/fontpie#9]
Now Fontpie only works with two options of font-family — 'serif' and 'sans-serif'. But web have at least two more — 'monospace' and 'handwriting'. Could you please adding their support?

**Comment by sashasushko** [comment]
Thank you, @nikvoblikov. We'll satisfy this feature request at one of the next fontpie releases

**Comment by lnikell** [comment]
Fixed as a part of #11
